name: "onnx_model"
backend: "python"
max_batch_size : 1
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "res"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
